name: Code Quality Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # This action sets up Python
  
    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install your Python dependencies
  
    - name: Lint Check
      run: pylint main.py --disable import-error

    - name: Format Check
      run: black --check main.py