name: "Pylint Check - Python"

on:
  pull_request:

jobs:
  pylint_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # This action sets up Python
  
    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install your Python dependencies
  
    - name: Lint Check
      run: pylint main.py --disable import-error