name: TODO Checker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Simple TODO Checker
        uses: ./  # Use the action defined in the repository
        with:
          path: "/.env"  # Path relative to the repository root
          extensions: ".py,.js"  # Optional: specify file types
          todo_pattern: "(#|//|/\\*|<!--|;|%)\\s*TODO"  # Optional: custom pattern
