name: TODO Checker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Simple TODO Checker
        uses: ./  # Use the action defined in the repository
        with:
          path: "."  # Path relative to the repository root
